title: .NET South East
description: .NET South East is a new .NET and C# meetup group in Brighton, UK.
keywords: dotnetsoutheast, .net, dotnet, dotnetcore, dotnetrenaissance, c#, csharp, microsoft, meetup, user group, madgex, brighton, uk
url: https://dotnetsoutheast.com

# source: ./
destination: ./www
include: [_indices]
exclude: [_layouts/default.html, _includes/sprite.symbol.svg, README.md, postcss.config.js, package.json, package-lock.json, LICENSE, config.yml, node_modules, webpack.config.js]
keep_files: [assets/js, assets/css, assets/fonts, index.html, _indices/home.markdown, _includes/sprite.symbol.svg, _layouts/default.html]
profile: true

# Defaults
defaults:
  - scope:
      type: archives
    values:
      permalink: /:path/
      layout: post
