title: .NET South East
description: .NET South East based in Brighton, England.
url: https://dotnetsoutheast.com

# source: ./
destination: ./www
include: [_indices]
exclude: [assets/scripts, assets/scss, node_modules]
keep_files: [assets/js/main.js, assets/css/main.css]
profile: true

# Defaults
defaults:
  - scope:
      type: archives
    values:
      permalink: /:path/
      layout: post
